<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '2016公司元宵节活动',
    'style' => '',
    'thumb' => 'http://localhost/phpcms_v9_UTF8/install_package/uploadfile/2017/0523/20170523093344621.png',
    'keywords' => '公司',
    'description' => '正月十五闹元宵，红红火火过小年。元宵佳节之际，到处洋溢着热闹的新春喜庆气息，每到这一天，人们都会以吃元宵、猜灯谜、逛花市、赏花灯等   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms_v9_UTF8/install_package/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1495546109',
    'updatetime' => '1495549841',
    'hitsid' => 'c-1-1',
    'views' => '6',
    'yesterdayviews' => '0',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '2015公司圣诞活动',
    'style' => '',
    'thumb' => 'http://localhost/phpcms_v9_UTF8/install_package/uploadfile/2017/0523/20170523093312379.png',
    'keywords' => '公司',
    'description' => '12月25号，公司举行了庆祝圣诞节砸金蛋的活动。整个活动持续了一个小时，每个员工脸上都挂着笑容，感觉空气中都洋溢了节日的气氛。   为   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms_v9_UTF8/install_package/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1495546158',
    'updatetime' => '1495549852',
    'hitsid' => 'c-1-2',
    'views' => '6',
    'yesterdayviews' => '0',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '9',
    'typeid' => '0',
    'title' => '2015秋公司聚餐活动',
    'style' => '',
    'thumb' => 'http://localhost/phpcms_v9_UTF8/install_package/uploadfile/2017/0523/20170523093156749.jpg',
    'keywords' => '',
    'description' => '由于明天下雨，我们原计划去苏州阳澄湖吃蟹的活动暂时取消。看到陶主任发在群里的这个消息，满脑子富得流油的大闸蟹瞬间被石化瓦解了。当办   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms_v9_UTF8/install_package/index.php?m=content&c=index&a=show&catid=9&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1495546078',
    'updatetime' => '1495549301',
    'hitsid' => 'c-1-3',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
);
?>